apiVersion: v1
kind: Service
metadata:
  name: armiarma-crawler
spec:
  selector:
    app: armiarma-crawler
  ports:
    - protocol: TCP
      name: crawler
      port: 9020
      targetPort: 9020
    - protocol: TCP
      name: prometheus
      port: 9090
      targetPort: 9090
  externalIPs:
    - 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: armiarma-eth2-crawler-test
spec:
  selector:
    matchLabels:
      app: armiarma-crawler
  serviceName: "eth2-crawler"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: armiarma-crawler
    spec:
      containers:
      - name: ant-crawler
        image: migalabs/armiarma-crawler:v1.0.0
        args: ["--config-file=./config-files/armiarma.json"]
        ports:
        - containerPort: 9020
          hostPort: 9020
          name: crawler
        - containerPort: 9080
          hostPort: 9080
          name: prometheus-endp
        volumeMounts:
        - name: armiarma-pvc
          mountPath: /armiarma/peerstore
        - name: armiarma-volume
          mountPath: /armiarma/config-files
      - name: prometheus-metrics
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
          hostPort: 9090
          name: prometheus-d
        volumeMounts:
        - name: prometheus-v
          mountPath: /etc/prometheus
      volumes:
        - name: armiarma-volume
          configMap:
            name: armiarma-config
        - name: prometheus-v
          configMap:
            name: prometheus-config
  volumeClaimTemplates:
  - metadata:
      name: armiarma-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: csi-cinder-high-speed
      resources:
        requests:
          storage: 1Gi
